import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}): JSX.Element => {
  return (
    <html lang="en">
      <body>
        <header className="flex w-full bg-inherit sm:sticky sm:top-0 sm:z-10">
          <div className="container mx-auto flex min-h-[80px] flex-wrap items-center justify-between gap-4 p-4">
            <Link href="/">
              <p className="whitespace-nowrap text-2xl font-bold underline">
                App Router Hands-on
              </p>
            </Link>
            <nav className="flex flex-wrap items-center gap-x-4 gap-y-1">
              <Link href="/static">Static</Link>
              <Link href="/dynamic">Dynamic</Link>
              {/*
              <Link href="/client-component" prefetch={false}>
                ClientComponent
              </Link>
              */}
            </nav>
          </div>
        </header>
        <main className="w-full">{children}</main>
      </body>
    </html>
  )
}

export default RootLayout
